#!/bin/bash

# ============================================================================
# Install the /wsg/ grabber: system dependencies plus a launcher on PATH.
# ============================================================================

set -euo pipefail

SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_NAME
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
readonly REPO_ROOT
readonly LAUNCHER="/usr/local/bin/wsg-grabber"

# mpv provides the player; tk provides the window. Both are runtime-only, and
# the package deliberately depends on neither via pip: python-mpv resolves
# libmpv at import time and would break any machine without it.
readonly PACKAGES=(mpv tk)

usage() {
    echo "Usage: $SCRIPT_NAME [--uninstall]"
    echo "  Installs mpv + tk and a 'wsg-grabber' launcher."
    exit 0
}

require_root() {
    if [[ $EUID -ne 0 ]]; then
        echo "Error: needs root to write $LAUNCHER and install packages." >&2
        echo "Re-run with: sudo $0" >&2
        exit 1
    fi
}

install_packages() {
    local missing=()
    local package
    for package in "${PACKAGES[@]}"; do
        if ! pacman -Qq "$package" &>/dev/null; then
            missing+=("$package")
        fi
    done
    if [[ ${#missing[@]} -eq 0 ]]; then
        echo "System packages already present: ${PACKAGES[*]}"
        return
    fi
    echo "Installing: ${missing[*]}"
    pacman -S --needed --noconfirm "${missing[@]}"
}

write_launcher() {
    cat > "$LAUNCHER" <<EOF
#!/bin/bash
# Launcher for the /wsg/ grabber. Generated by $SCRIPT_NAME.
set -euo pipefail
export PYTHONPATH="$REPO_ROOT\${PYTHONPATH:+:\$PYTHONPATH}"
exec python3 -m python_pkg.wsg_grabber "\$@"
EOF
    chmod 755 "$LAUNCHER"
    echo "Installed $LAUNCHER"
}

uninstall() {
    rm -f "$LAUNCHER"
    echo "Removed $LAUNCHER"
    echo "Downloaded videos in ~/.local/share/wsg_grabber were left alone."
}

main() {
    require_root
    install_packages
    write_launcher
    echo
    echo "Done. Try:"
    echo "  wsg-grabber stats"
    echo "  wsg-grabber          # opens the reviewer"
}

case "${1:-}" in
    -h|--help) usage ;;
    --uninstall) require_root; uninstall ;;
    "") main ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
esac
